name       : haskell-hastache
version    : 0.6.1
release    : 2
source     :
    - http://hackage.haskell.org/package/hastache-0.6.1/hastache-0.6.1.tar.gz : 8c8f89669d6125201d7163385ea9055ab8027a69d1513259f8fbdd53c244b464
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell implementation of Mustache templates
description: |
    Haskell implementation of Mustache templates
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-ieee754
    - haskell-mtl
    - haskell-syb
networking : yes
setup      : |
    sed -i "s|4.9|4.11|" hastache.cabal
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
